Initial Commit for v1.1.0
fortinet-fortisoar/connector-proofpoint-trap pull request #2
Opened 2024-11-18 06:01 UTC by cs-adarsh-gupta

### Descriptions:
- New action: Close Incidents
- Debug logs added.
- Internal logic is changed for function Get Incidents.

#### Affected Actions:
- [ ] Close Incidents

#### UTCs:
- [ ] Connector installation verified
- [ ] Connector logo verified
- [ ] Check health verified
- [ ] Docs link verified
- [ ] Actions and Playbooks list verified
- [ ] Playbook tags verified
- [ ] All playbooks are in info mode verified
- [ ] All playbooks are in inactive mode verified
- [ ] Ingestion playbooks are verified
- [ ] Verified platform dependencies remain unaffected

2024-11-21 07:22 UTC, cs-utkarsh-surana requested changes

2024-11-21 07:22 UTC, cs-utkarsh-surana commented on docs/ProofpointTRAP.md
> -</td></tr><tr><td>Closed After Date</td><td>Retrieve incidents that were closed after specified date, in ISO 8601 format (UTC)
Mention this under release notes.

2024-11-21 07:22 UTC, cs-utkarsh-surana commented on docs/ProofpointTRAP.md
> +</td></tr><tr><td>Email Message ID</td><td>Specify comma separated value of multiple message-ids.
Add details about this parameter in release notes.

2024-11-21 07:22 UTC, cs-utkarsh-surana commented on docs/ProofpointTRAP.md
> -</td></tr><tr><td>Cclosed Before Date</td><td>Retrieve incidents that were closed before specified date, in ISO 8601 format (UTC)
This as well.

2024-11-21 07:22 UTC, cs-utkarsh-surana commented on proofpoint-trap/info.json
>    "publisher": "Fortinet",
add contributor key

2024-11-21 07:22 UTC, cs-utkarsh-surana commented on proofpoint-trap/utils.py
> +        logger.error('RESPONSE STATUS CODE = {}'.format(str(response.status_code)))
set it to debug (both)

2024-11-22 08:41 UTC, cs-adarsh-gupta commented on proofpoint-trap/info.json
>    "publisher": "Fortinet",
Contributor key here is not valid, as the contributor has left the organisation

2024-11-22 09:04 UTC, merged